version: '2'
services:
  mjpg_streamer:
    build: cogwerx-mjpg-streamer-pi3/
    image: octoprint/mjpg_streamer
    container_name: mjpg_streamer
    privileged: true
    restart: unless-stopped
    ports:
      - 8080:8080
    entrypoint:
      - ./mjpg_streamer
      - -o
      - "output_http.so -w ./www"
      - -i
      - "input_raspicam.so -x 640 -y 480 -fps 20 -awb sun"
  octoprint:
    # This container also has HAPROXY set up for:
    #   80:/webcam  --> 8080:
    #   80:* --> 5000
    build: .
    image: octoprint/octoprint
    container_name: octoprint
    privileged: true
    restart: unless-stopped
    ports:
      - 5000:5000
      - 80:80
    volumes:
     - ./config:/home/octoprint/.octoprint
     - /dev:/dev


# docker run -it --rm --privileged -p 8080:8080 ms ./mjpg_streamer -o "output_http.so -w ./www" -i "input_raspicam.so -x 640 -y 480 -fps 20 -ex night"
