accessControl:
  autologinAs: petonic
  autologinLocal: true
  enabled: true
  localNetworks:
  - 127.0.0.0/8
  - 192.168.86.0/24
  userManager: octoprint.users.FilebasedUserManager
api:
  allowCrossOrigin: true
  key: 1D8DF67AD9594E81A44830CF33936F55
events:
  enabled: true
  subscriptions:
  - command:
    - switch_gpio 18 off
    event: Startup
    type: system
  - command: switch_gpio 18 on
    event: PrintStarted
    type: system
  - command: switch_gpio 18 off
    event: PrintFailed
    type: system
  - command: switch_gpio 18 off
    event: PrintCancelled
    type: system
  - command: switch_gpio 18 off
    event: PrintDone
    type: system
plugins:
  announcements:
    _config_version: 1
    channels:
      _blog:
        read_until: 1513605600
      _important:
        read_until: 1509547500
      _octopi:
        read_until: 1499253000
      _plugins:
        read_until: 1519603200
      _releases:
        read_until: 1513079100
  cura:
    cura_engine: /opt/cura/CuraEngine
  discovery:
    upnpUuid: 452f54a5-65e9-4251-918d-578923a26612
  softwareupdate:
    _config_version: 6
    check_providers:
      malyan_connection_fix: malyan_connection_fix
      systemcommandeditor: systemcommandeditor
printerProfiles:
  default: _default
serial:
  additionalPorts:
  - /dev/ttyACM0
  autoconnect: true
  baudrate: 115200
  port: /dev/ttyACM0
server:
  firstRun: false
  onlineCheck:
    enabled: true
  pluginBlacklist:
    enabled: true
  secretKey: Dnk5IiOXoMl7ZeKWLDugMEwjjgW3uWtE
  seenWizards:
    corewizard: 3
    cura: null
    softwareupdate: null
slicing:
  defaultProfiles:
    cura: ultimaker
webcam:
  ffmpeg: ''
  flipH: true
  flipV: true
  snapshot: http://127.0.0.1:8080/webcam/?action=snapshot
  stream: http://127.0.0.1:8080/webcam/?action=stream
  watermark: false
server:
  commands:
    ledOn: switch_gpio 18 on
    ledOff: switch_gpio 18 off
  firstRun: false
  onlineCheck:
    enabled: true
  pluginBlacklist:
    enabled: true
  secretKey: l7FM5ko1FjzWnBPr8Dy9iuArUX4J9c1Z
  seenWizards:
    corewizard: 3
    cura: null
    telegram: 1
system: {}
temperature:
  profiles:
  - bed: '80'
    extruder: '240'
    name: ABS
  - bed: '50'
    extruder: '210'
    name: PLA
